### ISSUE TITLE
Extend AT creation with osfamily setting

### ISSUE THREAD

**Issue by Nuanda** [dice-cyfronet/atmosphere#148]

**Comment by mkasztelnik** [comment]
Is it connected only with admin view or also with atmo rest API?

**Comment by Nuanda** [comment]
Actually that is a more serious thing. It looks like we should reuse appliance.dev_mode_property_set.os_family for that, when API-creating an AT. The API docs specify, that appliance_id is required when API-creating an AT.

The specs, however, seem to be at odds with that, see https://github.com/dice-cyfronet/atmosphere/blob/master/spec/requests/atmosphere/api/appliance_types_spec.rb#L634

So, should I change the specs to reject at POST with no appliance_id?

**Comment by mkasztelnik** [comment]
@Nuanda I believe that it is ok. Admin is able to create `Appliance Type` similar as it is done in admin UI. After `Appliance Type` is created already existing Virtual Machine Type can be attached to new created `Appliance Type`.

But you are right it is more serious thing and it is blocker for deployment into vph production (cc @nowakowski)  :( `OsFamily` should be assigned to new created `Appliance Type` most probably in [this](https://github.com/dice-cyfronet/atmosphere/blob/master/app/models/atmosphere/appliance_type.rb#L149-L161) method (it will be used though the Rest API). 

Additionally most probably Admin UI should be extended and allow admin to select `OsFamily`.

I can deal with `ApplianceType.create_from` if you like.

@nowakowski out of curiosity why `OsFamily` is attached into `ApplianceType` and not to `VirtualMachineTemplate`?

**Comment by Nuanda** [comment]
I already took care for the UI part. I can use some help with the API part.

**Comment by nowakowski** [comment]
Since the method linked by @mkasztelnik receives an `Appliance` object as its argument it should be a relatively straightforward matter of reusing `appliance.dev_mode_property_set.os_family`. We've already discussed this matter with @Nuanda earlier today.

Regarding your other question: I decided to make `os_family` an attribute of `ApplianceType` rather than of `VirtualMachineTemplate` as it seemed absurd to me that a single `ApplianceType` would have templates running different types of OS'. Accordingly, moving `os_family` to `VirtualMachineTemplate` seems like needless duplication of data, which is against good DB design principles.

**Comment by mkasztelnik** [comment]
It was a false alarm. os_family_id is copied correctly in [`Atmosphere::ApplianceType.appliance_type_attributes](https://github.com/dice-cyfronet/atmosphere/blob/master/app/models/atmosphere/appliance_type.rb#L185-L197). The only thing missing is to remove possibility to create AT without VMT by admin

**Comment by mkasztelnik** [comment]
I removed possibility to create AT without `appliance_id` by admin. 

Unfortunately there is a lot of failing tests (@Nuanda did you test it after https://github.com/dice-cyfronet/atmosphere/commit/948676f815205aed195136b875c9b8c5d0797b33 ?). The main reason is that AT factory is not correct (it does not create `OsFamily`). Unfortunately fixing factory does not solve the problem, because `Optimizer` and `Billing` failed with very ugly exceptions (e.g. `undefined method `>' for nil:NilClass`, `undefined method `/' for nil:NilClass`).

**Comment by mkasztelnik** [comment]
All tests fixed, changes can be reviewed
